### ISSUE TITLE
OpenMM-Torch package is incompatible with OpenMM 7.6

### ISSUE THREAD

**Issue by raimis** [conda-forge/openmm-plumed-feedstock#11]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

OpenMM-Torch package is incompatible with OpenMM 7.6:
```bash
mamba create -q -n tmp -c conda-forge openmm=7.6 openmm-plumed
Encountered problems while solving:
  - package openmm-plumed-1.0-py36h13eb63c_1 requires openmm >=7.5,<7.6.0a0, but none of the providers can be installed
```
Works as expected:
```bash
$ mamba create -q -n tmp -c conda-forge openmm=7.5 openmm-plumed
```

**Comment by jaimergp** [comment]
Yes, this is intended because of ABI compatibility. We need a rebuild for OpenMM 7.6.
